/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stokgudang.client.dialog;

import dao.adminDao;
import entity.Admin;
import java.awt.event.KeyEvent;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Riki subagja
 */
public class JD_Login extends javax.swing.JDialog {

    /**
     * Creates new form JD_Login
     */
    private adminDao adminDAO;
    private Admin admin;
    
    public JD_Login(adminDao admindao) {
        setModal(true);
        this.adminDAO = admindao;
        initComponents();
    }
    
    public Admin tampil(){
        setTitle("Login");
        setLocationRelativeTo(getParent());
        setVisible(true);
        return admin;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_usernama = new javax.swing.JTextField();
        bt_masuk = new javax.swing.JButton();
        bt_batal = new javax.swing.JButton();
        txt_password = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Silahkan Masukkan Username dan Password");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Silahkan Masukkan Username dan Password");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stokgudang/client/img/icon/People.png"))); // NOI18N
        jLabel2.setText("Username");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stokgudang/client/img/icon/Car key.png"))); // NOI18N
        jLabel3.setText("Password");

        txt_usernama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_usernamaKeyPressed(evt);
            }
        });

        bt_masuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stokgudang/client/img/icon/OK.png"))); // NOI18N
        bt_masuk.setText("Login");
        bt_masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_masukActionPerformed(evt);
            }
        });
        bt_masuk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_masukKeyPressed(evt);
            }
        });

        bt_batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stokgudang/client/img/icon/Close.png"))); // NOI18N
        bt_batal.setText("Cancel");
        bt_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_batalActionPerformed(evt);
            }
        });
        bt_batal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_batalKeyPressed(evt);
            }
        });

        txt_password.setToolTipText("Password");
        txt_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passwordKeyPressed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(102, 153, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_usernama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                            .addComponent(txt_password, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(88, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bt_masuk, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_batal)
                        .addGap(85, 85, 85))))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_usernama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_masuk, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_batal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_masukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_masukActionPerformed
        // TODO add your handling code here:
        if(txt_usernama.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Username masih Kosong");
        }else if(txt_password.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Password Masih Kosong !");
        }else{
            try {
                String usernama = txt_usernama.getText();
                String pass = new String(txt_password.getPassword());
                Admin a = new Admin();
                a.setUser_name(usernama);
                a.setUser_pass(pass);
                admin = adminDAO.getadminLogin(a);
                if(admin==null){
                    JOptionPane.showMessageDialog(null, "Username/Password yang dimasukkan salah!");
                }else{
                    dispose();
                }
            } catch (RemoteException e) {
                Logger.getLogger(JD_Login.class.getName()).log(Level.SEVERE,null,e);
            }
        }
    }//GEN-LAST:event_bt_masukActionPerformed

    private void bt_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_batalActionPerformed
        // TODO add your handling code here:
        admin = null;
        System.exit(0);
    }//GEN-LAST:event_bt_batalActionPerformed

    private void txt_usernamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usernamaKeyPressed
        
    }//GEN-LAST:event_txt_usernamaKeyPressed

    private void bt_masukKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_masukKeyPressed
        // TODO add your handling code here:
         if(txt_usernama.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Username masih Kosong");
        }else if(txt_password.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Password Masih Kosong !");
        }else{
            try {
                String usernama = txt_usernama.getText();
                String pass = new String(txt_password.getPassword());
                Admin a = new Admin();
                a.setUser_name(usernama);
                a.setUser_pass(pass);
                admin = adminDAO.getadminLogin(a);
                if(admin==null){
                    JOptionPane.showMessageDialog(null, "Username/Password yang dimasukkan salah!");
                }else{
                    dispose();
                }
            } catch (RemoteException e) {
                Logger.getLogger(JD_Login.class.getName()).log(Level.SEVERE,null,e);
            }
        }
    }//GEN-LAST:event_bt_masukKeyPressed

    private void bt_batalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_batalKeyPressed
        // TODO add your handling code here:
        admin = null;
        System.exit(0);
    }//GEN-LAST:event_bt_batalKeyPressed

    private void txt_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(txt_usernama.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Username masih Kosong");
            }else if(txt_password.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Password Masih Kosong !");
            }else{
                try {
                    String usernama = txt_usernama.getText();
                    String pass = new String(txt_password.getPassword());
                    Admin a = new Admin();
                    a.setUser_name(usernama);
                    a.setUser_pass(pass);
                    admin = adminDAO.getadminLogin(a);
                    if(admin==null){
                        JOptionPane.showMessageDialog(null, "Username/Password yang dimasukkan salah!");
                    }else{
                        dispose();
                    }
                } catch (RemoteException e) {
                    Logger.getLogger(JD_Login.class.getName()).log(Level.SEVERE,null,e);
                }
            }
        }
    }//GEN-LAST:event_txt_passwordKeyPressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_batal;
    private javax.swing.JButton bt_masuk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_usernama;
    // End of variables declaration//GEN-END:variables
}
